### ISSUE TITLE
PyPi hosted package does not contain zahner_analysis/anaylsis_tools

### ISSUE THREAD

**Issue by HudsonMC16** [Zahner-elektrik/Zahner-Analysis-Python#1]
zahner_analysis/file_import and zahner_analysis/plotting are there, however:

![image](https://user-images.githubusercontent.com/34110053/179764938-2bf7cc46-8582-4ef0-ac6c-62ba834380cd.png)

**Comment by maxkrapp1** [comment]
Thank you for your pull request, I have merged this one.
