### ISSUE TITLE
publish REST API specification

### ISSUE THREAD

**Issue by ilka-schulz** [Zahner-elektrik/Zahner-Analysis-Python#3]
This project looks promising and it may relieve the pain I have with BioLogic's proprietary software. However, buying a Zahner device would only be feasible if this project gets more functionality. I would be fine with implementing further functions myself and opening PRs but in order to do that I would need to know the specification of the REST API.

Something like [OpenAPI/Swagger](https://de.wikipedia.org/wiki/OpenAPI) would be awesome.

~~At this early point, I would also appreciate any information about which operations are supported by the REST API. E.g. is it possible to start measurements via the API?~~ (I see that there are other repos like [Thales-Remote-Python](https://github.com/Zahner-elektrik/Thales-Remote-Python) for controlling devices.)

**Comment by maxkrapp1** [comment]
Thank you for your inquiry and that you think our project is promising.

Our software the [Zahner Analysis](https://zahner.de/products-details/software/zahner-analysis) provides the analysis functions (at the moment only EIS fitting) via the [REST interface](https://doc.zahner.de/zahner_analysis/analysis_connection.html). Only Zahner file formats are supported.
This python package currently has no functions other than those provided by [Zahner Analysis](https://zahner.de/products-details/software/zahner-analysis) via the REST interface, except for plotting and importing Zahner measurement data. In the future we will extend this package and the REST API of the  [Zahner Analysis](https://zahner.de/products-details/software/zahner-analysis) with more functions.

We plan to document the API for the [Zahner Analysis](https://zahner.de/products-details/software/zahner-analysis) in the future. Thank you for pointing us to Swagger, as we have not yet decided on a tool to create the documentation.
At the moment the documentation to control the [Zahner Analysis](https://zahner.de/products-details/software/zahner-analysis) with REST unfortunately has to be taken from the Python source code of the classes, as we have not yet created any public documentation.

- The class [EisFitting](https://github.com/Zahner-elektrik/Zahner-Analysis-Python/blob/main/zahner_analysis/analysis_tools/eis_fitting.py) fits with the REST API, here you can see how the JSON messages are put together.
- The class [AnalysisConnection](https://github.com/Zahner-elektrik/Zahner-Analysis-Python/blob/main/zahner_analysis/analysis_tools/analysis_connection.py) wraps the python post and get functions of the requests package and automatically assembles the correct url.

The Zahner Analysis also provides a web page when you start the remote evaluation, which allows the fitting via the REST API. This web page also shows how the JSON is structured with the parameters.

You have seen it right, there is the package [Thales-Remote-Python](https://github.com/Zahner-elektrik/Thales-Remote-Python) with which our [ZENNIUM](https://zahner.de/products#potentiostats) devices can be controlled and the package [Zahner-Remote-Python](https://github.com/Zahner-elektrik/Zahner-Remote-Python) with which PP2x2, EL1002 and XPOT2 can be controlled without a [ZENNIUM](https://zahner.de/products#potentiostats).
Almost all functions of the devices can be controlled via the Python packages. For this, many detailed examples are available as Jupyter notebooks in the repos.

**Comment by ilka-schulz** [comment]
@maxkrapp1 Thank you very much for the detailed information! I will have a look at it in January with my colleagues but judging from what I saw so far, I am probably going to advocate for Zahner devices instead of BioLogic devices for our laboratory.

> Almost all functions of the devices can be controlled via the Python packages. For this, many detailed examples are available as Jupyter notebooks in the repos.

The accessibility via an open, complete and functioning API could potentially really make a difference in our laboratory workflows. I cannot express how glad I am that Zahner made the decision to make their devices' functionality accessible via an API.

**Comment by maxkrapp1** [comment]
With commit 63584f394ffb68c07ee5827a5bc3bbcbc1d6dbe the [swagger file](https://github.com/Zahner-elektrik/Zahner-Analysis-Python/blob/main/openapi.yaml) was added. The documentation as html is hosted at this [url](https://doc.zahner.de/zahner_analysis/analysis_remote.html).
